name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.vscode'
      - '.dockerignore'
      - 'Dockerfile'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Save PFX file
        env:
          CERT_PFX: ${{ secrets.CERT_PFX }}
        shell: powershell
        run: |
          [System.Convert]::FromBase64String("${env:CERT_PFX}") | Set-Content certificate.pfx -Encoding Byte

      - name: Build Release Files
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}